export const GET_ERRORS = "GET_ERRORS";
export const GET_GROUPS = "GET_GROUPS";
export const GET_GROUP = "GET_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";

export const GET_MOVIELISTS = "GET_MOVIELISTS";
export const GET_MOVIELIST = "GET_MOVIELIST";
export const DELETE_MOVIELIST = "DELETE_MOVIELIST";

export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIE = "GET_MOVIE";
export const DELETE_MOVIE = "DELETE_MOVIE";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_INVITATIONS = "GET_INVITATIONS";
export const GET_INVITATION = "GET_INVITATION";
export const DELETE_INVITATION = "DELETE_INVITATION";
export const ACCEPT_INVITATION = "ACCEPT_INVITATION";
